config/routes.rb
Nearme::Application.routes.draw do
  resources :recommendations

  resources :point_of_interests

  resources :users

end

app/models/point_of_interest.rb
class PointOfInterest < ActiveRecord::Base
  has_many :recommendations, :dependent => :destroy

  geocoded_by :address

  after_create :geocode_later
  after_create :recommend_to_nearby_people_later

  def close!
    recommendations.destroy_all
  end

  def recommend_to_nearby_people!
    sleep rand * 4  # Recommending is even harder!
    User.near(self, 5).each do |u|
      u.recommendations.create(:point_of_interest => self)
    end
  end

  def recommend_to_nearby_people_later
    Job.new(:model => 'PointOfInterest', :action => 'recommend_to_nearby_people!', :id => id)
  end

  def geocode_later
    Job.new(:model => 'PointOfInterest', :action => 'geocode!', :id => id)
  end

  def geocode!
    sleep rand * 2    # geocoding is hard work!
    geocode && save
  end

end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :user
  belongs_to :point_of_interest
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recommendations, :dependent => :destroy

  geocoded_by :address

  after_create :geocode_later
  after_create :seed_initial_recommendations_later

  def seed_initial_recommendations_later
    Job.new(:model => 'User', :action => 'seed_initial_recommendations!', :id => id)
  end

  def geocode_later
    Job.new(:model => 'User', :action => 'geocode!', :id => id)
  end

  def geocode!
    sleep rand * 2   # geocoding is hard work, you know.
    geocode && save
  end

  def seed_initial_recommendations!
    sleep rand * 4   # recommending is even harder!
    PointOfInterest.near(self, 5).each do |poi|
      self.recommendations.create(:point_of_interest => poi)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/point_of_interests_controller.rb
class PointOfInterestsController < ApplicationController
  # GET /point_of_interests
  # GET /point_of_interests.json
  def index
    @point_of_interests = PointOfInterest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @point_of_interests }
    end
  end

  # GET /point_of_interests/1
  # GET /point_of_interests/1.json
  def show
    @point_of_interest = PointOfInterest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @point_of_interest }
    end
  end

  # GET /point_of_interests/new
  # GET /point_of_interests/new.json
  def new
    @point_of_interest = PointOfInterest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @point_of_interest }
    end
  end

  # GET /point_of_interests/1/edit
  def edit
    @point_of_interest = PointOfInterest.find(params[:id])
  end

  # POST /point_of_interests
  # POST /point_of_interests.json
  def create
    @point_of_interest = PointOfInterest.new(params[:point_of_interest])

    respond_to do |format|
      if @point_of_interest.save
        format.html { redirect_to @point_of_interest, notice: 'Point of interest was successfully created.' }
        format.json { render json: @point_of_interest, status: :created, location: @point_of_interest }
      else
        format.html { render action: "new" }
        format.json { render json: @point_of_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /point_of_interests/1
  # PUT /point_of_interests/1.json
  def update
    @point_of_interest = PointOfInterest.find(params[:id])

    respond_to do |format|
      if @point_of_interest.update_attributes(params[:point_of_interest])
        format.html { redirect_to @point_of_interest, notice: 'Point of interest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @point_of_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /point_of_interests/1
  # DELETE /point_of_interests/1.json
  def destroy
    @point_of_interest = PointOfInterest.find(params[:id])
    @point_of_interest.destroy

    respond_to do |format|
      format.html { redirect_to point_of_interests_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  # GET /recommendations
  # GET /recommendations.json
  def index
    @recommendations = Recommendation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recommendations }
    end
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show
    @recommendation = Recommendation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recommendation }
    end
  end

  # GET /recommendations/new
  # GET /recommendations/new.json
  def new
    @recommendation = Recommendation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recommendation }
    end
  end

  # GET /recommendations/1/edit
  def edit
    @recommendation = Recommendation.find(params[:id])
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    @recommendation = Recommendation.new(params[:recommendation])

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully created.' }
        format.json { render json: @recommendation, status: :created, location: @recommendation }
      else
        format.html { render action: "new" }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recommendations/1
  # PUT /recommendations/1.json
  def update
    @recommendation = Recommendation.find(params[:id])

    respond_to do |format|
      if @recommendation.update_attributes(params[:recommendation])
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    @recommendation = Recommendation.find(params[:id])
    @recommendation.destroy

    respond_to do |format|
      format.html { redirect_to recommendations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/point_of_interests_helper.rb
module PointOfInterestsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nearme</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/point_of_interests/_form.html.erb
<%= form_for(@point_of_interest) do |f| %>
  <% if @point_of_interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point_of_interest.errors.count, "error") %> prohibited this point_of_interest from being saved:</h2>

      <ul>
      <% @point_of_interest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/point_of_interests/edit.html.erb
<h1>Editing point_of_interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @point_of_interest %> |
<%= link_to 'Back', point_of_interests_path %>

app/views/point_of_interests/index.html.erb
<h1>Listing point_of_interests</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Name</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @point_of_interests.each do |point_of_interest| %>
  <tr>
    <td><%= point_of_interest.address %></td>
    <td><%= point_of_interest.name %></td>
    <td><%= point_of_interest.latitude %></td>
    <td><%= point_of_interest.longitude %></td>
    <td><%= link_to 'Show', point_of_interest %></td>
    <td><%= link_to 'Edit', edit_point_of_interest_path(point_of_interest) %></td>
    <td><%= link_to 'Destroy', point_of_interest, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Point of interest', new_point_of_interest_path %>

app/views/point_of_interests/new.html.erb
<h1>New point_of_interest</h1>

<%= render 'form' %>

<%= link_to 'Back', point_of_interests_path %>

app/views/point_of_interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @point_of_interest.address %>
</p>

<p>
  <b>Name:</b>
  <%= @point_of_interest.name %>
</p>

<p>
  <b>Latitude:</b>
  <%= @point_of_interest.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @point_of_interest.longitude %>
</p>


<%= link_to 'Edit', edit_point_of_interest_path(@point_of_interest) %> |
<%= link_to 'Back', point_of_interests_path %>

app/views/recommendations/_form.html.erb
<%= form_for(@recommendation) do |f| %>
  <% if @recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
      <% @recommendation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :point_of_interest_id %><br />
    <%= f.number_field :point_of_interest_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recommendations/edit.html.erb
<h1>Editing recommendation</h1>

<%= render 'form' %>

<%= link_to 'Show', @recommendation %> |
<%= link_to 'Back', recommendations_path %>

app/views/recommendations/index.html.erb
<h1>Listing recommendations</h1>

<table>
  <tr>
    <th>User</th>
    <th>Point of interest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recommendations.each do |recommendation| %>
  <tr>
    <td><%= recommendation.user_id %></td>
    <td><%= recommendation.point_of_interest_id %></td>
    <td><%= link_to 'Show', recommendation %></td>
    <td><%= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
    <td><%= link_to 'Destroy', recommendation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recommendation', new_recommendation_path %>

app/views/recommendations/new.html.erb
<h1>New recommendation</h1>

<%= render 'form' %>

<%= link_to 'Back', recommendations_path %>

app/views/recommendations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @recommendation.user_id %>
</p>

<p>
  <b>Point of interest:</b>
  <%= @recommendation.point_of_interest_id %>
</p>


<%= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
<%= link_to 'Back', recommendations_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.address %></td>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @user.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @user.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @user.longitude %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Recommendations:</b>
  <ul>
    <%- @user.recommendations.each do |rec| %>
      <%- poi = rec.point_of_interest %>
      <li><%= link_to poi.name, poi %></li>
    <%- end %>
  </ul>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>